import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Inter } from "next/font/google";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import "./globals.css";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "FrontEnd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <head>
        {/* ฟอนต์ไทย: Charmonman, Itim, Pattaya, Sriracha */}
        <link
          href="https://fonts.google.com/share?selection.family=Charmonman:wght@400;700|Itim|Pattaya|Sriracha"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${inter.variable} antialiased`}
        style={{
          fontFamily:
            "'Charmonman', 'Itim', 'Pattaya', 'Sriracha', 'Inter', sans-serif",
        }}
      >
        <div className="container-fluid">
          <div className="row">
            <div className="col">
              <Navigation />
            </div>
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
