import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Inter } from "next/font/google";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import "./globals.css";

// ฟอนต์ภาษาอังกฤษ
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "FrontEnd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <head>
        {/* ฟอนต์ภาษาไทย Prompt */}
        <link
          href="https://fonts.googleapis.com/css2?family=Prompt:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.variable} antialiased`} style={{ fontFamily: "'Prompt', 'Inter', sans-serif" }}>
        <div className="container-fluid">
          <div className="row">
            <div className="col">
              <Navigation />
            </div>
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
